configName: sam_rh71_ek
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMRH71F20C
projectName: ''
settings:
  PackageFilter: aerospace;audio;bootloader;bootloader_apps_ethernet;bootloader_apps_uart;bsp;core;crypto;csp;csp_apps_sam_rh71;gfx;gfx_apps;motor_control;net
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMRH71_DFP\2.2.112\samrh71c\atdf\ATSAMRH71F20C.atdf
