package:
  format-version: "1.0.0"
  name: "aerospace"
  type: "api"
  status: "production"
  required: true
  version: "3.5.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.18.2"
