package:
  format-version: "1.0.0"
  name: "aerospace"
  type: "api"
  status: "production"
  required: true
  version: "3.4.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.13.1"
    - name: "dev_packs"
      type: "package"
      version: "3.13.0"
